---
title: "City Genres"
output: html_document
date: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## World Map

Text

```{r, echo=FALSE, include=FALSE, message=FALSE, warning=FALSE}
library(devtools)
devtools::install_github("rstudio/leaflet")
library(leaflet)
library(leaflet.extras)
library(leaflet.extras2)
library(readr)
library(tidyverse)
library(dplyr)
library(RColorBrewer)
library(ggplot2)
library(sf)
library(tmap)
library(patchwork)
library(grid)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Import data
data <- read_csv("data/all_data.csv")

# Create pop-up content
pop_content <- paste("City Name: ", data$city_name, "<br/>",
                     "Longitude: ", data$longitude, "<br/>",
                     "Latitude: ", data$latitude, "<br/>")

# Create a leaflet map
leaflet(data) %>%
  setView(lng=mean(data$longitude), lat=mean(data$latitude), zoom=2) %>%
  addProviderTiles("Stamen.TonerLite") %>%
  addCircleMarkers(popup=pop_content, clusterOptions=markerClusterOptions(),
                   color="#F8D664")
```


## Key Patterns

### Number of Visitors in 2019
```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Change column names
colnames(data)[9] <- "visitor_2019_million"
colnames(data)[21] <- "winter_sports"
colnames(data)[22] <- "sea_sports"
colnames(data)[23] <- "old_town"
colnames(data)[26] <- "horseback_riding"
colnames(data)[28] <- "climate_type"
colnames(data)[30] <- "dec_feb_temp"
colnames(data)[31] <- "jun_aug_temp"
colnames(data)[32] <- "near_unesco"
colnames(data)[35] <- "todo_30"
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Filter the top 10 cities by number of visitors in 2019
top10 <- data %>%
  arrange(desc(visitor_2019_million)) %>%
  mutate(rank=row_number()) %>%
  filter(rank<=10)

# Create a bar chart
ggplot(top10, aes(x=reorder(city_name, visitor_2019_million), y=visitor_2019_million)) +
  geom_bar(stat="identity", fill="#F8D664") +
  coord_flip() +
  labs(x="",
       y="Number of Visitors (in million)",
       caption=element_text("Data Source: World Tourism Organization")) +
  geom_text(aes(label=visitor_2019_million),
            vjust=0.3,
            hjust=-0.05,
            show.legend=FALSE) +
  theme_classic() +
  theme(axis.line.y=element_blank(),
        axis.line.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.title=element_text(hjust=0.5, vjust=5),
        plot.caption=element_text(hjust=0.5),
        plot.margin=unit(c(1,-0.1,0,-0.4), "cm")) +
  expand_limits(y=c(0,90)) +
  plot_annotation(
    title="Top 10 Destinations by Visitors in 2019",
    theme = theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"))
  )
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Create density plot for displaying temperature distribution
# Temp for dec to feb
dec_feb <- ggplot(data, aes(x=dec_feb_temp)) +
  geom_density(color="white", fill="#F8D664", alpha=0.5) +
  labs(x="Dec. to Feb. Avg Temp (°F)",
       y="") +
  theme_classic() +
  theme(axis.line.y=element_blank(),
        axis.line.x=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.y=element_blank(),
        plot.title=element_text(hjust=0.5, vjust=5),
        plot.caption=element_text(hjust=0.5),
        plot.margin=unit(c(1,-0.1,0,-0.4), "cm")
        )

# Temp for jun to aug
jun_aug <- ggplot(data, aes(x=jun_aug_temp)) +
  geom_density(color="white", fill="#F8D664", alpha=1) +
  labs(x="Jun. to Aug. Avg Temp (°F)",
       y="") +
  theme_classic() +
  theme(axis.line.y=element_blank(),
        axis.line.x=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.y=element_blank(),
        plot.title=element_text(hjust=0.5, vjust=5),
        plot.caption=element_text(hjust=0.5),
        plot.margin=unit(c(1,-0.1,0,-0.4), "cm")
        )

# Patchwork
plot <- (dec_feb + jun_aug) +
  plot_annotation(
    title="Distribution of the Average Temperature",
    theme = theme(plot.title = element_text(hjust = 0.5, size = 16, face="bold"))
  )
plot
```

```{r}
# Find unique values of climate_type
data$climate_type <- tolower(data$climate_type)
unique(data$climate_type)

# Count cities of each climate type
climate_group <- data %>%
  group_by(climate_type) %>%
  summarize(count=n()) %>%
  arrange(desc(count))

# Define colors
my_colors <- c("#fcf1cc", "#fae7a5", "#f9dc7e", "#f7d257", "#f5c830",
            "#f2bc0a", "#ca9e09", "#a37f07", "#7c6105", "#554303")

# Create a bar chart
ggplot(climate_group, aes(x = reorder(climate_type, count), y = count)) +
  geom_bar(fill = my_colors, stat = "identity") +
  coord_flip() +
  xlab("") +
  ylab("Number of Cities") +
  labs(caption="Data Source: Wikipedia") +
  geom_text(aes(label=count),
            vjust=0.3,
            hjust=-0.1,
            show.legend=FALSE) +
  theme_classic() +
  theme(axis.line.y=element_blank(),
        axis.line.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.title=element_text(hjust=0.5, vjust=5),
        plot.caption=element_text(hjust=0.5)) +
  plot_annotation(
    title="Distribution of Climate Types",
    theme = theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"))
  )

```
## Other Patterns

```{r}

```

## City Clusters

```{r}

```


## Text Analysis

```{r}
# Analyze two text sources separately
library(stringr)
library(tm)
library(wordcloud)
library(wordcloud2)
library(textstem)

# Import cleaned data
data_t <- data
#data_t <- data_t %>%
  #filter(beach==0)
trip_text <- data_t$trip_clean
wiki_text <- data_t$para_clean
```

```{r}
table(data$beach)
```


```{r}
# To corpus
docs_trip <- Corpus(VectorSource(trip_text))
docs_wiki <- Corpus(VectorSource(wiki_text))

# Calculate frequencies
dtm_trip <- DocumentTermMatrix(docs_trip)
dtm_wiki <- DocumentTermMatrix(docs_wiki)
m_trip <- as.matrix(dtm_trip)
m_wiki <- as.matrix(dtm_wiki)
freq_trip <- sort(colSums(m_trip), decreasing=TRUE)
freq_wiki <- sort(colSums(m_wiki), decreasing=TRUE)
df_trip <- data.frame(freq_trip=names(freq_trip), freq=freq_trip)
df_wiki <- data.frame(freq_wiki=names(freq_wiki), freq=freq_wiki)

# Define color for word cloud
wc.color <- c("#7c6105", "#f2bc0a", "#f9dc7e")

# Filter words
df_trip <- df_trip %>%
  filter(freq>5)
df_wiki <- df_wiki %>%
  filter(freq>700)

# Define "same length" function
rep.len <- function(x, length.out) {
  rep(x, length.out = length.out)
}
```


```{r}
wordcloud2(df_trip,
           color=rep.len(wc.color, nrow(df_trip)),
           rotateRatio=0)
```
```{r}
wordcloud2(df_wiki,
           color=rep.len(wc.color, nrow(df_wiki)),
           size=1.5,
           rotateRatio=0)
```

```{r}
# Word cloud
trip_wc <- wordcloud(names(freq_trip), freq_trip, max.words=50, colors=my_colors)
wiki_sc <- wordcloud(names(freq_wiki), freq_wiki, max.words=50, colors=my_colors)

# Patchwork
plot <- (trip_wc + wiki_sc) +
  #plot_annotation(
    #title="Word Clouds of Text Data",
    #theme = theme(plot.title = element_text(hjust = 0.5, size = 16, face="bold"))
  #)
plot
```

## Conclusions


